source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '5.0.6'
# Use Puma as the app server
gem 'puma', '~> 3.4'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'

gem 'concurrent-ruby', '1.0.5'

# Use jquery as the JavaScript library
gem 'jquery-rails', '~> 4.1'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
# gem 'turbolinks', '~> 5.x'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# UserAgent によるデバイス判定およびビューの振り分け
gem 'rack-user_agent', '~> 0.5.2'

# Redis
gem 'redis-rack', '~> 2.0.2'
gem 'redis-store', '~> 1.4.0'
gem 'redis-rails'

# paging用
gem 'kaminari', '0.17.0'

# 非同期処理用
gem 'delayed_job', '~> 4.1.4'
gem 'delayed_job_active_record', '~> 4.1.1'
gem 'daemons', '~> 1.2.3'

# Unicode正規化ライブラリ
gem 'unicode', '>= 0.4.0'

# XML-RPC
gem 'xmlrpc'

group :development, :test do
  # pry関連(デバッグなど便利)
  gem 'pry-rails'    # rails cの対話式コンソールがirbの代わりにリッチなpryになる
  gem 'pry-doc', '~> 0.12.0' # pry中に show-source [method名] でソース内を読める
  gem 'pry-stack_explorer'   # pry中にスタックを上がったり下がったり行き来できる
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  #gem 'byebug'
  gem 'hirb'         # モデルの出力結果を表形式で表示するGem
  gem 'hirb-unicode' # 日本語などマルチバイト文字の出力時の出力結果のずれに対応
end

group :development, :test do
  gem 'pry-byebug'   # binding.pryをソースに記載すると、ブレイクポイントとなりデバッグが可能になる
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 3.0'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'rack-mini-profiler', require: false
end

group :test do
  gem 'minitest', '5.10.3'  # 5.11.x 系にはバグがあるので、5.10.x 系を使う
  gem 'minitest-reporters' #テスト結果表示整形用
  gem 'simplecov'
  gem 'timecop'
  gem 'webmock' # テスト時の外部へのアクセスをモックする
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
#gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
